### ISSUE TITLE
Provide more details on how to set up registry keys for running release

### ISSUE THREAD

**Issue by corndog2000** [isledecomp/isle#1283]
In the README there is this brief section under Usage.

> Alternatively, LEGO Island can run from any directory as long as ISLE.EXE and LEGO1.DLL are in the same directory, and the registry keys (usually HKEY_LOCAL_MACHINE\Software\Mindscape\LEGO Island or HKEY_LOCAL_MACHINE\Software\Wow6432Node\Mindscape\LEGO Island) point to the correct location for the asset files.

It would be very helpful for people trying to compile and run the program if there were screenshots included showing how to set up these registry keys correctly.

**Comment by Ramen2X** [comment]
It's a little bit complicated to set up the registry keys manually if you're not familiar with the game's internals. Right now, I recommend just running `CONFIG.EXE` once to populate the registry properly for you. Alternatively, you can just install the original game and replace `ISLE` and `LEGO1` in the installation directory; this is what is intended, since the binaries are not meant to run on their own just like the original game.

**Comment by mrpenguinb** [comment]
Having an option to make a portable install, or have the registry be a config file stored with the game's executable, could be an option. Would have to exclude the feature from the accuracy measurements for the decomp though.

**Comment by Ramen2X** [comment]
> Having an option to make a portable install, or have the registry be a config file stored with the game's executable, could be an option.

This is already implemented in our [isle-portable](https://github.com/isledecomp/isle-portable) repo since it is outside the scope of the decompilation.

**Comment by mrpenguinb** [comment]
I completely forgot about the portable repo. Thanks for reminding everyone.

**Comment by Ramen2X** [comment]
Closing since I've clarified the usage instructions in the README.
